### ISSUE TITLE
Add support for Spring service implementation templates

### ISSUE THREAD

**Issue by averabaq** [cjbooms/fabrikt#11]
Add a `cli` option for generating the Spring service implementations with empty body templates. Something like:

```
@Service
class MyResourceServiceImpl() : MyResourceService {
    override fun read(param1: String, param2: String?): Customer {
        TODO("Not Implemented Yet!")
    }
}
```

**Comment by cjbooms** [comment]
Let's migrate to Controller interface generation instead:
https://github.com/cjbooms/fabrikt/issues/30
