### ISSUE TITLE
Support naming controller methods after the operationId

### ISSUE THREAD

**Issue by Gama11** [cjbooms/fabrikt#111]
In openapi-generator, controller methods are named after the `operationId` in the spec file. fabrikt just seems to name the methods after the HTTP method (`post()` etc). This makes it impossible to implement multiple controllers with overlapping HTTP methods in the same class.

The simplest solution would be to use the `operationId` like openapi-generator does - perhaps as an option as it would be breaking otherwise?

I could also see wanting to have this feature even apart from the mentioned multiple-controllers-in-one-class use case, simply because the `operationId`, if present, is probably carries more information than the generated one.

**Comment by cjbooms** [comment]
Yep, that makes sense to me. We can just release a 3.0 version to indicate it may be a breaking change and code paths will need to be adjusted
