### ISSUE TITLE
Client return type is always nullable

### ISSUE THREAD

**Issue by Gama11** [cjbooms/fabrikt#120]
I noticed that the return type of clients is always nullable:

https://github.com/cjbooms/fabrikt/blob/fe780487196eb641eafac706d20b822098eae99b/src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt#L40

Is this simply a result of OkHttp's `response.body` being nullable? For endpoints that return something, it might be more sensible to throw an `ApiException` instead if the status code was 2xx but there was no body. Otherwise user code always needs a try-catch _and_ null handling, which seems annoying.

**Comment by averabaq** [comment]
Yes, we designed this way to make it flexible by letting the developer to decide what to do when there's no content in the response, like 201 & 204 cases for example. We could make the code-generator smarter though by forcing a non-nullable return type on those cases when there's only one `200` response definition. However, this may entail a breaking change for existing users and not fully sure about the benefits. This is one for @cjbooms

**Comment by Gama11** [comment]
Would it even be a breaking change? A nullable type is "broader" than a non-nullable one, so worst case there's some compiler warnings about unnecessary null checks?

**Comment by averabaq** [comment]
Agreed, my concern was more in line with potential existing implementations on the top that might be actually expecting a null on the body response. Fully agreed that's not "RESTFul" compliant but... Let's see what Conor says about it :)

**Comment by cjbooms** [comment]
I'm fine with changing it. We only use the generated client in test harnesses and if something breaks we can change it back easily enough.
