### ISSUE TITLE
allOf with single $ref leads to Any

### ISSUE THREAD

**Issue by Gama11** [cjbooms/fabrikt#121]
Code generation for the following example is correct (return types correctly typed as `Result`):

```yml
openapi: 3.0.0
paths:
  /test:
    get:
      operationId: test
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    Result:
      allOf:
        - $ref: '#/components/schemas/Base'
        - type: object
          properties:
            bar:
              type: string
    Base:
      properties:
        foo:
          type: string
```

However, when `Result` is reduced to just this, the return type in both the client and the controller is suddenly `Any`:

```yml
    Result:
      allOf:
        - $ref: '#/components/schemas/Base'
```

I think an `allOf` with a single item should be treated the same as a direct `$ref`.

**Comment by cjbooms** [comment]
The lack of `type: object` in Base is causing this to get treated like an AnyType now. It works if you change it to:
```
   Base:
      properties:
        foo:
          type: string
```

Perhaps we should treat a schema that defines properties as a `type: object` regardless

**Comment by Gama11** [comment]
Oh, right, somehow I missed that, even though I already found (and fixed) a bunch of these in our specs. Seems openapi-generator didn't care, not sure what the spec says about it (if anything).
