### ISSUE TITLE
Adding a companion object to generated data classes

### ISSUE THREAD

**Issue by rajki** [cjbooms/fabrikt#158]
Hey team,
I was wondering if this request would be considered reasonable. Currently while generating model classes, they are realized as data classes. While this already has benefits over regular Kotlin classes, it can be extended further. Given that Kotlin has the ability to add extension functions, the current realisation only allows for extension functions at the instance level. To enable fluent semantics, it would be an option to accommodate extension functions at the class level through the generation of a companion object.

The request is illustrated as below:
Source spec: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
Generated Pet model class:
```
package com.example.models
... imports

data class Pet(
... properties
)
```

The usage of this generated model class:
```
// regular code flow
return Pet(... values)
```

Generated model class after incorporating proposal:
```
package com.example.models
... imports

data class Pet(
... properties
)  {
  companion object
}
```

The enablement of class level extension functions:
```
fun Pet.Companion.from(... values) {
    return Pet(... values)
}

// regular code flow
return Pet.from(... values)
```

Please let me know what you think about this. I have a patch where I attempted this already and it works. I'll polish it and put out a PR in case I get a green signal.

**Comment by averabaq** [comment]
Thank you so much for this @rajki! ❤️  
This does makes sense to me and I think it'll be a very nice add-on. Since the proposal is just to introduce just the `companion object` clause on the models, it shouldn't entail any breaking change. Still not sure, if it might be good to put it under a `cli` option though 🤔 - waiting for @cjbooms to see what he thinks?

**Comment by cjbooms** [comment]
I see no issue with this. The only question is whether we should make it opt-in via config parameter or not?
```
--http-model-opts INCLUDE_COMPANION_OBJECT
```

**Comment by rajki** [comment]
I followed the suggestion and created a draft PR. Please take a look at your convenience.
