### ISSUE TITLE
Controllers: Add more flexibility on how to extract information from requests

### ISSUE THREAD

**Issue by atollk** [cjbooms/fabrikt#162]
At the moment, query parameters, headers, and request bodies are extracted into specific variables with their respective annotations; nothing more, nothing less. Spring (and Micronaut) also supports storing the entire request information in one single object. There is also an `Authentication` class to provide information about the authenticated user. Both of these can be retreived by also adding them to the parameter list of a controller function with their proper annotations.

I feel like it would be helpful to have additional controller options for things like "enable complete request", "enable authentication info", and "disable single variables".

**Comment by cjbooms** [comment]
It would be good to see a worked example of the signatures you are looking to have generated. I'm curious if there is an existing way to make use of these features when implementing the fabrikt-generated controller interfaces
 
Either way, I'm certainly open to this feature if you're willing to contribute it.

**Comment by atollk** [comment]
I'm not 100% sure I get your question.

These are two examples from the Micronaut user guide on how `HttpRequest` would be used. I'm not too familiar with Spring but from reading the documentation, I understand that it offers analogous objects.

```kotlin
@Controller("/request")
class MessageController {

    @Get("/hello") // (1)
    fun hello(request: HttpRequest<*>): HttpResponse<String> {
        val name = request.parameters
                          .getFirst("name")
                          .orElse("Nobody") // (2)
    
        return HttpResponse.ok("Hello $name!!")
                .header("X-My-Header", "Foo") // (3)
    }

}
```

Our specific use case is to allow the use of more generic utility functions to be called. For example, every endpoint of our API might offer a `reverse_order` parameter. Instead of having to manually pass that parameter everywhere, we could extract it from a generic `HttpRequest` object and encapsulate all complex logic from the controller functions.

**Comment by cjbooms** [comment]
To clarify:
Can you provide a list of all additional controller parameters you think would be useful? It's relatively easy to add new static parameters to the generated controller signatures, but I'm not sure which ones you desire or are compatible.

For Spring, I found [this list of acceptable arguments](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-arguments), and the `HttpRequest` class you list above is not one of them. Please validate that it would work correctly.

If you take an example from one of the existing test cases, and expand it with the parameters you desire, I'll add the code generation feature. 
[This example](https://github.com/cjbooms/fabrikt/blob/master/src/test/resources/examples/githubApi/controllers/spring/Controllers.kt#L73-L84):
```
    @RequestMapping(
        value = ["/contributors"],
        produces = ["application/json"],
        method = [RequestMethod.GET]
    )
    fun searchContributors(
        @Min(1) @Max(100) @RequestParam(value = "limit", required = false, defaultValue = "10")
        limit: Int,
        @RequestHeader(value = "X-Flow-Id", required = false) xFlowId: String?,
        @RequestParam(value = "include_inactive", required = false) includeInactive: Boolean?,
        @RequestParam(value = "cursor", required = false) cursor: String?
    ): ResponseEntity<ContributorQueryResult>
```

Would become something like:
```
    @RequestMapping(
        value = ["/contributors"],
        produces = ["application/json"],
        method = [RequestMethod.GET]
    )
    fun searchContributors(
        request: HttpRequest,
        @Min(1) @Max(100) @RequestParam(value = "limit", required = false, defaultValue = "10")
        limit: Int,
        @RequestHeader(value = "X-Flow-Id", required = false) xFlowId: String?,
        @RequestParam(value = "include_inactive", required = false) includeInactive: Boolean?,
        @RequestParam(value = "cursor", required = false) cursor: String?
    ): ResponseEntity<ContributorQueryResult>
```
 

> ```kotlin
> request: HttpRequest<*>
> ```

eques

**Comment by atollk** [comment]
You're right, my bad. The classes I was referring to are called `HttpEntity` (https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpEntity.html) and `Authentication` (https://docs.spring.io/spring-security/site/docs/4.0.x/apidocs/org/springframework/security/core/Authentication.html) in Spring.

I'll come back with more details.

**Comment by atollk** [comment]
**Regarding the entire request body**

For Micronaut, a new parameter is added to endpoint methods:
```
@Get
fun example(
  httpRequest: HttpRequest<T>,
) {/* ... */}
```

"T" in this example, refers to the body type, i.e. the "DTO" that could also be injected by using the `@Body` annotation.
For endpoints that accept no body, e.g. usual "GET" requests, we use `*` instead, i.e. `HttpRequest<*>`.

For Spring, this is almost the same, just that we use `HttpEntity` rather than `HttpRequest`.


**Regarding the authentication object** (this one is more complicated)

The `securitySchema` tags can be ignored by Fabrikt. Only the `security` tags are relevant. These can be defined both on operation/endpoint level as well as on a global API level. If both are defined, the former takes precedence for those operations over the latter. Fabrikt needs to consider both to provide the correct behavior.

For each endpoint, we then distinguish four cases:

First case: No security. This happens if no `security` is defined on either level or if the defined security is an empty array, i.e. `[]`. 

Second case: Authentication required. This happens if `security` is defined and contains any element that is not the empty object `{}`.

Third case: Authentication prohibited. This happens if `security` is defined and contains only the empty object `{}`.

Fourth case: Authentication optional. This happens if `security` is defined and contains the empty object `{}` as well as any element that is not the empty object.

For Micronaut, the four cases described above cause the following effects:

First case: No security. The endpoint method does not change.

```kotlin
@Get
fun example() {/* ... */}
```

Second case: Authentication required. The `@Secured` annotation with `SecurityRule.IS_AUTHENTICATION` is added as well as the `Authentication` parameter.

```kotlin
@Get
@Secured(SecurityRule.IS_AUTHENTICATED)
fun example(
  authentication: Authentication
) {/* ... */}
```

Third case: Authentication prohibited. The `@Secured` annotation with `SecurityRule.IS_ANONYMOUS` is added.

```kotlin
@Get
@Secured(SecurityRule.IS_ANONYMOUS)
fun example() {/* ... */}
```

Fourth case: Authentication optional. The `@Secured` annotation with `SecurityRole.IS_ANONYMOUS` and `SecurityRule.IS_AUTHENTICATED` is added. The `Authentication` parameter is added but is nullable.

```kotlin
@Get
@Secured(SecurityRule.IS_ANONYMOUS, SecurityRule.IS_AUTHENTICATED)
fun example(
  authentication: Authentication?
) {/* ... */}
```

For Spring, it's almost the same as for Micronaut as described above. The only two differences are:

* use the Spring `Authentication` object, obviously (i.e. `org.springframework.security.core.Authentication` instead of `io.micronaut.security.authentication.Authentication`
* there is no `@Secured` annotation or equivalent; so we just need to generate the parameter

-----

I'll see that I'll provide a PR for this change including more examples hopefully soon.
