### ISSUE TITLE
Type String, format binary generates String in Kotlin instead of ByteArray

### ISSUE THREAD

**Issue by cgraving** [cjbooms/fabrikt#163]
OpenAPI 3.0 spec says to use type/format combinations of string/binary or string/byte for files and images. These generate to String in Kotlin instead of ByteArray.

Open API examples
```
"schema": {
  "type": "string",
  "format": "byte"
}

"schema": {
  "type": "string",
  "format": "binary"
}
```

Current Generated (Spring Response Example)
`  public fun download(@PathVariable(value = "path", required = true) path: String): ResponseEntity<String>`

Expected Generated (Spring Response Example)
`  public fun download(@PathVariable(value = "path", required = true) path: String): ResponseEntity<ByteArray>`

**Comment by cjbooms** [comment]
I agree that ByteArray makes sense when the format is `byte`, and this can easily be added in this PR:
https://github.com/cjbooms/fabrikt/pull/166/files

However, I am not sure about binary. Isn't that used for file uploads only?

**Comment by cgraving** [comment]
https://swagger.io/docs/specification/data-models/data-types/#file

So, in my quick testing the `ResponseEntity<ByteArray>` works perfectly with returning the file using `StreamUtils.copyToByteArray(image.inputStream)` which is ByteArray.

When I return base64 encoded data as a string, `ResponseEntity<String>` and `Base64.getEncoder().encodeToString(bytes)` as the body, it does not work.

If I change it to `ResponseEntity<ByteArray>` and return `Base64.getEncoder().encode(bytes)` as base64 bytes, then it also does not work.

I would tend to be OK with whatever is deemed as best and matches standards. 

Thanks! Quick PR turnaround and I will test it and make sure it works for my use cases.

**Comment by cgraving** [comment]
Sounds good to me. I am happy with your PR for my needs with byte.

**Comment by cjbooms** [comment]
Closing this issue as it is addressed for Byte. A new issue can be opened if file upload for binary types is needed
