### ISSUE TITLE
Unable to generate files with Norwegian letters øåø

### ISSUE THREAD

**Issue by alpet** [cjbooms/fabrikt#167]
Hei, I have been trying to make fabrikt generate files with utf-8 encoding by passing file encoding to the file generation task but without luck. The files generated do not contain norwgian charactes øæå . Am I setting the encoding wrong ?

tasks {
    val generateCode by creating(JavaExec::class) {
        print(apiFile)
        inputs.files(apiFile)
        outputs.dir(generationDir)
        outputs.cacheIf { true }
        classpath(fabrikt)
        main = "com.cjbooms.fabrikt.cli.CodeGen"
        jvmArgs?.add("-Dfile.encoding=UTF-8")
        args = listOf(
            "--output-directory", generationDir,
            "--base-package", "xxxxxxxxx",
            "--api-file", apiFile,
            "--targets", "http_models",
            "--http-client-opts", "resilience4j"
        )
    }

**Comment by alpet** [comment]
Here is an example of generated code

  @get:JsonProperty("årsakInnsending")
  val rsakInnsending: RsakInnsending? = null
  
  Filename should be ÅrsakInnsending

**Comment by alpet** [comment]
I tryed with  

jvmArgs=listOf("-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8","-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=1044")
        environment.put("LC_ALL", "nb_NO.utf-8")
        
      No luck.

**Comment by cjbooms** [comment]
I'd say something needs to change in the [Normalised string class](https://github.com/cjbooms/fabrikt/blob/4bce82ca08bc85baf51e5f391723d53a2995f078/src/main/kotlin/com/cjbooms/fabrikt/util/NormalisedString.kt)

**Comment by alpet** [comment]
The regex private fun String.replaceSpecialCharacters() =
        Regex("[^A-Za-z0-9]").replace(this, "_") iswrong most probably. The first and the last character in Norwegian alpghabet are   A-Å

**Comment by alpet** [comment]
Unfortunatly I am having problems building the project. The tests are failing on my machine. I am relativly new to Kotlin and at the same time my locale is Norwegian, that may as well have something to do with it. I am tring to fingure it out.

**Comment by cjbooms** [comment]
I don't have the time today to craft a proper regex, but here is a quick and dirty PR to unblock you. 
https://github.com/cjbooms/fabrikt/pull/168
Please double-check that all your characters are supported.

**Comment by alpet** [comment]
Will it be published in a repo so I can fetch it or ?

**Comment by alpet** [comment]
Yes thanks, the characters look good.

**Comment by alpet** [comment]
That would be great thanks!

**Comment by alpet** [comment]
Hei I would like to say thank you for your fast response. And I think I have one a little bit more generic solution so that not only norwegian characters are capchurd but possibly for example baltic or cyrrilic or whatever:

private fun String.replaceSpecialCharacters() =
        Regex("[^\\p{L}^\\d]").replace(this, "_")

    private fun String.camelToSnake() =
        Regex("[\\p{Lower}][\\p{Upper}]")
            .replace(this) { pair ->
                val characters = pair.value.toCharArray()
                "${characters[0]}_${characters[1]}"
                
               I hope this works.
