### ISSUE TITLE
The classes extending the sealed class to be inlined inside the sealed class

### ISSUE THREAD

**Issue by alpet** [cjbooms/fabrikt#172]
I red that one of the main use cases for sealed class is to function as enum classes in a way. If that is so does not it make sense for the implementation of polymorphism to be:

sealed Superclass {

data class SubtypeA: Superclass

data class SubtypeB: Superclass
}

This way we can later access the two subtypes via  Superclass.SubtypeA and Superclass.SubtypeB effectivly it starts functioning similar to enum

PS; I noticed that when companion object configuration is set a companion object is not generated in the Polymorphism case. Is this a bug ?

**Comment by cjbooms** [comment]
I'm sure there are pros and cons to both approaches, but that is my personal preference is not to nest as I don't like the longer signatures. Either way, I'd be reluctant to revisit the polymoprphic implementations for anything short of a bug, they are brittle and time-consuming to change.

Yes, I would say the lack of companion object is a  bug/oversight when we added it a few weeks ago.
