### ISSUE TITLE
Add possibility to select datetime type for generators

### ISSUE THREAD

**Issue by bykakashka** [cjbooms/fabrikt#176]
Currently only 'OffsetDateTime' used for model\client generators. It leads to conflicts if server or other client code uses Instant as a datetime type.

Suggestion:
Add `--type-options` parameter for generator, with `instant_datetime_type` possible value.
If this parameter exist - use Instant as a datetime type, otherwise use OffsetDateTime by default

**Comment by bykakashka** [comment]
Added PR, any thoughts? https://github.com/cjbooms/fabrikt/pull/177

**Comment by cjbooms** [comment]
Closed in #178
