### ISSUE TITLE
Support for jakarta.* validation annotations

### ISSUE THREAD

**Issue by rajki** [cjbooms/fabrikt#179]
Currently, the library adds `javax.validation.*` annotations which makes it compatible with 2.x of `jakarta.validation-api`. The most recent version of `jakarta.validation-api`, however is 3.x and has moved the annotations under the `jakarta.validation.*` namespace.

Question: how do you think the Fabrikt library should deal with this? 
* Support both 2.x and 3.x versions
* Upgrade to support 3.x version

**Comment by cjbooms** [comment]
I'm thinking we'll need to add an option to control which one gets generated, at least for a period of time until mass adoption of Jakarta annotations.

**Comment by cjbooms** [comment]
> JFYI: The code change itself was pretty straightforward and I'm almost done with them. Hit up on an interesting problem while writing tests. There are some dependencies which are placed to ensure that the kotlin classes in the tests folder do not complain about missing classes. I'll probably have to find a way to isolate the tests for jakarta into a separate source set which has the 3.x dependency and not the 2.x dependency.

I'd say just add one single test for whatever is the non-default validation option, and remove any conflicting test dependencies entirely. We have a few examples single tests that validate different behaviour, see

**Comment by cjbooms** [comment]
Closed in #180 

I can't release this right now as Github actions are down:
https://twitter.com/githubstatus/status/1641103440318169093
