### ISSUE TITLE
Support for custom validation annotations

### ISSUE THREAD

**Issue by thomas-weinstein-bosch** [cjbooms/fabrikt#202]
Hello,

is there currently some way (didn't find it in the documentation) or if not are there plans to support custom validation annotations?
E.g. in the sense of https://www.baeldung.com/java-swagger-custom-validation 

An example usecase would be an extended validation for free text strings. It would be preferable to have it in the generated models - I was checking if there are some ways to customize the generation process, but didn't find a way to do so. If it could be part of the specification that would be a nice addon, as the client using the API would already be informed which extended validations (more than the simple size / length / ... validations) are in place.

Would be interesting to get your view if this is seen in scope of the library and if so, which way (supporting it in the API specification or with a configuration option in the build process somehow) you see most fitting.

Thank you in advance.

**Comment by cjbooms** [comment]
I don't know if this is general enough to warrant inclusion in fabrikt. 
If I were you and needed some custom annotations, I would write a gradle script to edit the generated classes afterwards. 

Here is an example where I've done something like this in the past:
```
    val makeJacksonSuperTypesMutable by registering {
        // This task exists because the graalvm ReflectionConfigurationResources are not working when the target field is a val in a jackson supertype.
        doLast {
            listOf("DatabaseAuthentication", "Flow", "Sink", "Source")
                .map {
                    buildDir
                        .resolve(generationDir)
                        .resolve(generatedSrcPath)
                        .resolve("ie/zalando/fabric/fes/operator/models/$it.kt")
                }
                .filter { it.exists() }
                .forEach { file ->
                    file.writeText(file.readText().replace("val type: String", "var type: String"))
                }
        }
    }

    val generateApiModels by creating(FabriKt::class) {
        apiFile = "$projectDir/src/main/resources/metacontroller-operator-api.yaml"
        args = listOf(
            "--output-directory", outputDirectory,
            "--src-path", srcPath,
            "--base-package", "ie.zalando.fabric.fes.operator",
            "--api-file", apiFile,
            "--targets", "HTTP_MODELS",
            "--http-model-opts", "X_EXTENSIBLE_ENUMS",
            "--http-model-opts", "QUARKUS_REFLECTION"
        )
        finalizedBy(makeJacksonSuperTypesMutable)
    }

```

**Comment by cjbooms** [comment]
Closing this issue. But if you think of an elegant way to include this I'm open to any PRs you want to contribute.

**Comment by thomas-weinstein-bosch** [comment]
thanks! we will try the way with the additional gradle script.
