### ISSUE TITLE
Example usage of calling service layer

### ISSUE THREAD

**Issue by magna25** [cjbooms/fabrikt#207]
Thanks for the great library. I have fabrikt setup locally and it generates the controllers and models fine howerver the controllers are only interfaces and there is no call to the service layer. is that part supposed to be done manually? I have used openapi-generator gradle plugin before with templates and it was able to do that. any help or guidance how to achieve something similar?

here is what i get from the generated controller:
```kotlin

@Controller
@Validated
@RequestMapping("/v2")
interface PetController {
  /**
   * Add a new pet to the store
   *
   * @param pet Pet object that needs to be added to the store
   */
  @RequestMapping(
    value = ["/pet"],
    produces = ["application/json"],
    method = [RequestMethod.POST],
    consumes = ["application/json"]
  )
  fun addPet(@RequestBody @Valid pet: Pet): ResponseEntity<Pet>
}
```
I have a service named `PetService` and with the method `addPet` and i'm trying to call that method from the controller

**Comment by thomas-weinstein-bosch** [comment]
Yes, that is the good thing about only generating interfaces, you have the contract specified, but the interactions with the service layer you can easily do in the Implementation of the Interface, e.g.:

@Controller
class PetControllerImpl (
    private var petService: PetService
) : PetController {
    
    @Override
    override fun addPet(pet: Pet): ResponseEntity<Pet> {
        return ResponseEntity(petService.addPet(), HttpStatus.OK)
    }
}
