### ISSUE TITLE
Subtype without new properties doesn't become data class.

### ISSUE THREAD

**Issue by ePaul** [cjbooms/fabrikt#216]
**Situation**

I got a polymorphic type with a bunch of subtypes (using the discriminator feature, with an x-extensible-enum `type`).
Most of the subtypes add new properties (via allOf).
For one of the subtypes, no additional properties are needed (so it only has the type).

**Expected behavior**

All of the subtypes get generated as Kotlin data classes, extending a common super class, so two parsed object trees can be compared using `==` / `!=` (or Java's `.equals()`).

**Actual behavior**

For the subtype which doesn't add a new property, the generated class is missing the `data` keyword.

The impact of this is that after parsing the same YAML file twice, the generated object trees don't compare equal (if this subtype is used somewhere in the tree). In my project, this leads to a "change of config detected", so the server restarts all the time. _(Actually, this was caught by a test before rolling it out.)_

**Versions**

I've observed it with Fabrikt 7.3.0 as well as 8.10.0., so it's not a recent regression. (I just added a new subtype which triggered this).

**Comment by ePaul** [comment]
_(I'll try to create a minimal example for this tomorrow, now need to go to bed.)_

**Comment by cjbooms** [comment]
THis rings a bell:
https://github.com/cjbooms/fabrikt/pull/98

**Comment by ePaul** [comment]
@cjbooms This sounds like it, thanks. I guess I have such a marker use case, but I think that should still work with equals/hashCode (basically: all instances are equal). (Not sure what other functionality `data` provides here.)

**Comment by ePaul** [comment]
Ah, the problem is that you can't have a `data` class without a constructor parameter.
