### ISSUE TITLE
Doesn't pass tests on recent JRE, Kotlin compiler and Gradle.

### ISSUE THREAD

**Issue by rocket-matt** [cjbooms/fabrikt#227]
I'm new to the Java & Kotlin ecosystem so I may be doing something very wrong.  My environment (as installed using sdkman) is:

* Java 17.0.7 (Temurin)
* Kotlin 1.9.0
* Gradle 8.2.1

And I ran this command in a fresh clone:

```
./gradlew clean build
```

It seems to build, but then it executes the :test task and fails a lot.

[I've attached the test results here](https://github.com/cjbooms/fabrikt/files/12160010/test.zip)

**Comment by cjbooms** [comment]
Yes, it currently requires Java 11. I made a start at upgrading but requires some ralated changes that I never got around to finishing.
