### ISSUE TITLE
Feature Request: Additional query parameters in requests

### ISSUE THREAD

**Issue by hyperschwartz** [cjbooms/fabrikt#310]
I'm currently working with a fairly new API that is being developed by a third party, and they haven't specified all their applicable query parameters in their specification.  It would be great if the framework could support additional query parameters in the same way that header specifications are supplied, as an optional `Map<String, String>`.

**Comment by cjbooms** [comment]
Happy to accept a contribution if you can make the change

**Comment by hyperschwartz** [comment]
@cjbooms I'd be happy to!  I have it completely coded up locally, but I'm having issues (403 auth rejection) pushing my branch.  Perhaps I need to be added as a contributor manually?

**Comment by cjbooms** [comment]
Great stuff. You should be able to fork the repo ito your own local GitHub account, and create a PR from there to here

**Comment by hyperschwartz** [comment]
Thanks for the info!  Got this posted: https://github.com/cjbooms/fabrikt/pull/311
