### ISSUE TITLE
Add support for adding the Micronaut @Introspected annotation to the models

### ISSUE THREAD

**Issue by averabaq** [cjbooms/fabrikt#58]
Please add micronaut `@Introspected` annotation to the model classes in order to ease the integration with the Micronaut framework: https://docs.micronaut.io/1.2.6/guide/index.html#_making_a_bean_available_for_introspection

Perhaps a cli option similar to the one we use for `quarkus-reflection`?

**Comment by averabaq** [comment]
@cjbooms wdyt? would you be happy with me adding support for it? 
Note: It's only a nice-to-have, not a blocker so I can live with that 🙂

**Comment by cjbooms** [comment]
Sounds good! Go for it. Awesome to see you back 🥳
