### ISSUE TITLE
Provide minimal gradle plugin with task, and fix caching in example

### ISSUE THREAD

**Issue by rnett** [cjbooms/fabrikt#88]
The gradle task example in the readme does not play nice with Gradle's caching at all.  The worst case scenario is that the cache key is not dependent on the input files, so even after changing the spec a stale cache entry will be used.  This seems to be the case.

At a minimum, the example should be updated to use `inputs.file("/path-to-api/open-api.yaml").withPathSensitivity(PathSensitivity.NONE)`, but ideally you could provide a small gradle plugin with a task type that sets up proper caching and provides setters/configuration methods for the most common CLI options.

**Comment by cjbooms** [comment]
Interesting, this is not something I was aware of, thanks for the report. Would this issue be circumvented using clean?
`./gradlew clean generateCode`

I'll have a play and update the Readme if it's as simple as you suggest. 

I'd like to avoid maintaining custom tasks or plugins for individual build systems. I personally use Gradle and configure this in multiple projects and have not had complaint when using the `JavaExec` plugin. In one multi-module project, we define a custom plugin in the buildSrc directory as follows to reduce duplication:
```
import org.gradle.api.tasks.JavaExec

open class FabriKt : JavaExec()
```
```
plugins {
    kotlin("jvm")
}
repositories {
    mavenCentral()
}
val fabric: Configuration by configurations.creating
val generationDir = "$buildDir/generated"
dependencies {
    fabric("com.cjbooms:fabrikt:2.1.0")
}
sourceSets {
    main { java.srcDirs("$generationDir/src/main/kotlin") }
}
tasks {
    withType(FabriKt::class) {
        classpath(configurations.named("fabric"))
        mainClass.set("com.cjbooms.fabrikt.cli.CodeGen")
    }
}
```

But in most cases, there is only one gradle task generating code and it is inlined into the build script without complaint. 

What do you think? If you feel strongly that there should be a plugin for every build system, I'm open to considering it

**Comment by rnett** [comment]
Hmm, I think you're ok without a plugin if you update the example.  That said, the main reason I'd want one for gradle is for the caching, and maven doesn't have an equivalent that you'd need a plugin for.

> Would this issue be circumvented using clean?
./gradlew clean generateCode

No, in fact you'd probably need to run `clean` to see it (so it pulls from cache instead of up to date).

It's possible there's some inspection of JavaExec args for files that I'm not aware of, but I wouldn't expect this to play nice with caching as is.  An easy experiment: turn the build cache on, run `generateCode`, edit the openapi file, run `clean generateCode` and see whether the task is re-ran (`SUCCESS`) or pulled from cache (`FROM-CACHE`).

**Comment by normartin** [comment]
We use this task definition that utilizes the build cache:

```groovy
def swaggerSpec = "path to yaml"
def generatedSourcesDir = "${buildDir}/generated/swagger"

// ...

def generateApiClient = tasks.register("generateApiClient", JavaExec) {
    inputs.files(swaggerSpec)
    inputs.files(configurations.fabrikt)

    outputs.dir(generatedSourcesDir)
    outputs.cacheIf { true }

    classpath = configurations.fabrikt
    mainClass = "com.cjbooms.fabrikt.cli.CodeGen"
    args = [
            "--output-directory", generatedSourcesDir,
            "--base-package", "<your package here>",
            "--api-file", swaggerSpec,
            "--targets", "http_models",
            "--targets", "client"
    ]
}
```

**Comment by cjbooms** [comment]
I've updated some Zalando repos to use the Gradle cache feature and it's provided a nice build time improvements. It's cool watching it skip the generate-code tasks when nothing has changed. Thanks again for your report, it's had a positive impact on unrelated projects :)

I've used the following in a multi-module project to make it easier to share config and support the build cache:
```
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.JavaExec
import org.gradle.api.tasks.OutputDirectory

open class FabriKt : JavaExec() {
    @InputFile
    lateinit var apiFile: String

    @OutputDirectory
    lateinit var outputDirectory: String
}
```

**Comment by rnett** [comment]
👍 glad it helped.  You should add a `PathSensitivity(NONE)` to `apiFile` too (although it's not really relevant unless you have a remote cache), otherwise the same file at different locations will cause a cache miss.
