### ISSUE TITLE
Downloading a release and building it does not work -> missing .git folder

### ISSUE THREAD

**Issue by gregopet** [cjbooms/fabrikt#91]
I tried downloading the latest release from the Releases tab. When I tried building it, I got the following error:

```
* Where:
Build file '/home/gregor/src/fabrikt-2.1.1/build.gradle.kts' line: 4

* What went wrong:
An exception occurred applying plugin request [id: 'com.palantir.git-version', version: '0.12.3']
> Failed to apply plugin 'com.palantir.git-version'.
   > Cannot find '.git' directory
```

Running `git init .` helped and I could then build the project.

**Comment by cjbooms** [comment]
I have updated the readme to make this easier for the next engineer

**Comment by gregopet** [comment]
Great - I was wondering, would it be sensible to include the `.jar` itself in the release?
